import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getUser } from "./_actions/user-actions";
import Profile from "./_components/Profile/Profile";
import UserProvider from "./_context/users";
import { User } from "./_types/user-types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const userData: Promise<User> = getUser("1");
  const user: User = await userData;
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider user={user}>
        <Profile/>
        {children}
        </UserProvider>
      </body>
    </html>
  );
}
